### ISSUE TITLE
installing `pybind11` as a build time python package dependency

### ISSUE THREAD

**Issue by shubhbapna** [DS4SD/docling-parse#25]
When we try to build `docling-parse` from source, it tries to clone the `pybind11` repository and then set the includes path. However, we are running this build in a network isolated environment which causes the clone step to fail.

An alternate to this would be to install `pybind11` as a build time python package dependency and use its API in `build.py` to set it up:
- https://pybind11.readthedocs.io/en/stable/compiling.html#modules-with-setuptools
- https://github.com/octavifs/poetry-pybind11-integration

**Comment by tiran** [comment]
I made a similar change to Triton a while ago, https://github.com/triton-lang/triton/pull/4450
