### ISSUE TITLE
Support building against system libraries

### ISSUE THREAD

**Issue by tiran** [DS4SD/docling-parse#26]
docling-parse uses cmake's `ExternalProject_Add` feature to download 3rd dependencies at build time. The build system then vendors the 3rd binaries libraries into the wheel. We prefer to use system-provided libraries, so we can track the provenance of all dependencies. System libraries also allow us to address security issues without rebuilding all components.

Would it be possible to add a mode to use system-provided libraries via cmake `find_package()` or `pkgconfig`?

https://github.com/DS4SD/docling-parse/blob/8b7d0d6f9cb19f0c8a7f2871f0a087a90a2158e4/CMakeLists.txt#L100-L105

- utf8cpp has a cmake package provider
- libjpeg-turbo has cmake package and a pkgconfig provider
- nlohmann_json has cmake package and a pkgconfig provider
- libqpdf has a pkgconfig provider

**Comment by dolfim-ibm** [comment]
for testing it properly also in CI, we can use CentOS 9 Stream container with EPEL

for example:

```dockerfile
FROM quay.io/centos/centos:stream9
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && crb enable \
    && dnf clean all
RUN dnf install -y --nodocs \
        gcc gcc-c++ git make cmake ninja-build glibc-devel \
    && dnf clean all
```
