### ISSUE TITLE
Adding a new optimised v2 parser

### ISSUE THREAD

**Issue by staar** [DS4SD/docling-parse#30]
The current v1 parser is slow with regard to parsing documents, primarily due to a lot of inheritance. In the new v2, we will remove any inheritance and improve the parsing speed.

In addition, we would like to:

1. dynamically load the fonts (only load if necessary)
2. remove any inheritance
3. have the capability to switch between snippet and word level

**Comment by PeterStaar-IBM** [comment]
Integrated with the latest PR into main
