### ISSUE TITLE
non-compliant-utf8-text

### ISSUE THREAD

**Issue by bml1g12** [DS4SD/docling-parse#59]
Thanks for your contributions; it's a really exciting project!

I've tried docling on this example single page Japanese PDF 
[1 (1).pdf](https://github.com/user-attachments/files/17803663/1.1.pdf)

But the output contains many sections of text that are omitted and replaced with "non-compliant-utf8-text". It seems it originates from this repo:  https://github.com/DS4SD/docling-parse/blob/988318a45f86c512c600399907bb3d3b7e685ad9/src/pybind/docling_parser_v1.h#L299 

Do you know what the solution is to this issue? As far as I'm aware this document contains only very standard utf-8 characters, or at least no other library I've tried has had issues reading the text, and it can be safely copied and pasted to a text edit. 

Is docling suitable for Japanese text parsing I wonder?

**Comment by PeterStaar-IBM** [comment]
@bml1g12 Yes, in principle it should, but we will always find some broken ones, which we need to fix ;).

**Comment by PeterStaar-IBM** [comment]
Resolved here: https://github.com/DS4SD/docling-parse/pull/57

<img width="1430" alt="Screenshot 2024-11-29 at 17 24 07" src="https://github.com/user-attachments/assets/aec6696c-1c40-4eed-911b-68a1575deeb1">
