### ISSUE TITLE
page image preprocessing steps, not able to reproduce results

### ISSUE THREAD

**Issue by mllife** [DS4SD/docling-parse#70]
I am trying out your layout model "model_artifacts/layout/beehive_v0.0.5_pt/model.pt" but I am seeing completely different output. I see you have done the page recalling from 1.5x res back to original w, h in "get_page_image" method in pdf_backend. But I am still not getting the same output. Can you tell me what else I am missing?

**Comment by PeterStaar-IBM** [comment]
docling-parse is not using a model. This issue is in the wrong repo: closing.
